WAIT 3.
SET SHIP:CONTROL:PILOTMAINTHROTTLE TO 0.
BRAKES ON. CLEARSCREEN.
SWITCH TO 0.
RUN FORMAT. SWITCH TO 1.
COPY CLEARPLAN.KS FROM 0.
COPY MAIN.KS FROM 0.
COPY ORBNAV.KS FROM 0.
COPY GMN.KS FROM 0.
COPY DVR.KS FROM 0.
COPY DVF.KS FROM 0.
COPY GMN.KS FROM 0.
COPY GTISP.KS FROM 0.
COPY WRPTO.KS FROM 0.
COPY ORB.KS FROM 0.
COPY AP.KS FROM 0.
RENAME MAIN.KS TO BOOT.KS.
REBOOT.
