SET TETA TO 60*60*365*100.
SET TMN TO NODE(T+TETA,0,0,0). ADD TMN.
SET TMN:ETA TO TETA.
SET NN TO NEXTNODE.
IF NN=TMN {SET MN TO 0.} ELSE {SET MN TO NN.}
REMOVE TMN.
WAIT 1.
IF (MN:ETA>0.9*TETA) {SET MN TO 0.}
