DECLARE PARAMETER DESTTIME. SET DT TO DESTTIME-T. SET NWARP TO 0.
IF DT>10 {SET NWARP TO 1.}
IF DT>60 {SET NWARP TO 2.}
IF DT>300 {SET NWARP TO 3.}
IF DT>1200 {SET NWARP TO 4.}
IF DT>5000 {SET NWARP TO 5.}
IF DT>30000 {SET NWARP TO 6.}
IF DT>120000 {SET NWARP TO 7.}
IF SAS AND (WARP>0) {SET WARP TO 0.
} ELSE IF (NOT (WARP=NWARP)) AND CPUTHROT<=0 {
  IF (NWARP>0) AND (WARPMODE="PHYSICS") {
   IF ALTITUDE>70000 {SET WARPMODE TO "RAILS".}
  } SET WARP TO NWARP.
}
